### PR TITLE
fix: [TV] add last move highlights

### LINKED ISSUE #1026: Lichess TV games don't display board highlights
### What is the problem?

From the Forum:
On Lichess TV games, board highlights, king check highlights, etc don't display.

### Steps to reproduce the bug

Enter Lichess TV
Expected: Board highlights are shown
What Happened: board highlights are not shown

### App version

0.11.0

### Device Info

Pixel 6 and Android 14

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sid0-0**
~~Fixes #1026~~
feat: add last move highlights in TV

Created and passed `GameData` to display last move highlights and checks.

### CODE REVIEW

File: lib/src/view/watch/tv_screen.dart [hunk 1]
```diff
@@ -111,6 +113,21 @@ class _Body extends ConsumerWidget {
                       : null,
                   materialDiff: game.lastMaterialDiffAt(Side.white),
                 );
+
+                final gameAtCursor = game.positionAt(gameState.stepCursor);
+
+                final gameDataAtCursor = GameData(
```
Comment (veloce) [inline lib/src/view/watch/tv_screen.dart:119]: The `GameData` was meant only for boards that are playable. 

For now we can only display the `lastMove` which is already a great improvement. We'll only be missing the king check highlight which is not a big deal. I'll figure out what we can do with the chessground API later, to improve that.

Comment (sid0-0) [reply lib/src/view/watch/tv_screen.dart]: updated

**Review by veloce — APPROVED** [review]
