### PR TITLE
resolves #654

### LINKED ISSUE #654: "Has x seconds for his/her move" switches side depending on the side that currently plays
### What is the problem?

When starting a game and the opponent does not start playing instantly there appears a warning below their name.
The warning states that the player has x seconds until the game is aborted.

If you are white and go back a move (so to move 0 where no pieces have moved) the warning switches players and is now below my name.

### Steps to reproduce the bug

1. New Game
2. Be White
3. Play first move
4. Opponent does not play first move
5. Opponent gets warning "has x seconds to move"
6. "go back" one move
7. warning appears below my name

### What did you expect to happen?

warning stays below his/her name

### What happened instead?

warning switched to my name

### Device Info

OnePlus 8 Pro

### Operating System Version

Android 14

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Mauritz8**
resolves #654

### CODE REVIEW

File: lib/src/view/game/game_body.dart [hunk 1]
```diff
@@ -119,7 +119,7 @@ class GameBody extends ConsumerWidget {
     return gameStateAsync.when(
       data: (gameState) {
         final position = gameState.game.positionAt(gameState.stepCursor);
-        final sideToMove = position.turn;
+        final sideToMove = gameState.game.sideToMove;
```
Comment (veloce) [inline lib/src/view/game/game_body.dart:122]: The variable name adds confusion. 

I'd rather not declare it and pass `gameState.game.sideToMove` directly where it's needed.

**Review by veloce — COMMENTED** [review]
Good catch, thanks.

File: lib/src/view/game/game_body.dart (hunk 1 above)
Comment (Mauritz8) [reply lib/src/view/game/game_body.dart]: Now I have fixed it.

**Review by veloce — APPROVED** [review]
