### PR TITLE
Profile Fixes

### LINKED ISSUE #1514: Should there be share links for profiles?
Was hoping to grab one for a GitHub ticket but curious in general

### PR DESCRIPTION
**Pull request by HaonRekcef**
closes #1514 
Some improvements to the profile screen: 
- Players cant see if they are shadowbanned in their own profile 
- Do not convert new lines into spaces anymore, as the behavior changed on the website
- Add a share button to the profile screen

grafik

### CODE REVIEW

File: lib/src/view/account/profile_screen.dart [hunk 1]
```diff
@@ -60,6 +63,20 @@ class _ProfileScreenState extends ConsumerState<ProfileScreen> {
             semanticsLabel: context.l10n.editProfile,
             onPressed: () => Navigator.of(context).push(EditProfileScreen.buildRoute(context)),
           ),
+          account.when(
+            data: (user) => user == null
+                ? const SizedBox.shrink()
+                : SemanticIconButton(
+                    icon: const Icon(Icons.share),
```
Comment (veloce) [inline lib/src/view/account/profile_screen.dart]: Should use the `PlatformShareIcon` here.

File: lib/src/view/user/user_screen.dart [hunk 2]
```diff
@@ -93,12 +96,20 @@ class _UserScreenState extends ConsumerState<UserScreen> {
...
+      appBar: PlatformAppBar(
         title: UserFullNameWidget(
           user: updatedLightUser ?? widget.user,
           shouldShowOnline: updatedLightUser != null,
         ),
-        actions: [if (isLoading) const PlatformAppBarLoadingIndicator()],
+        actions: [
+          if (isLoading) const PlatformAppBarLoadingIndicator(),
+          SemanticIconButton(
+            icon: const Icon(Icons.share),
```
Comment (veloce) [inline lib/src/view/user/user_screen.dart]: Same: PlatformShareIcon.

**Review by veloce — APPROVED** [review]
