### PR TITLE
fix: hide study hint when changing chapter or correct move has been played

### LINKED ISSUE #2212: Hints in studies
### What is the problem?

When you take a hint in the studies, it doesn't disappear in subsequent chapters.

### Steps to reproduce the bug

1. Enter the study with an interactive mode and a hint.
2. Go to another chapter with a hint (or make a move).
3. See that the hint is not hidden.

### App version

?

### Device Info

?

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tom-anders**
Fixes #2212

### CODE REVIEW

File: lib/src/view/study/study_gamebook.dart [hunk 1]
```diff
@@ -90,8 +90,32 @@ class _Hint extends ConsumerStatefulWidget {
...
+    ref.listen(
+      studyControllerProvider(widget.id).select((state) => state.valueOrNull?.gamebookState),
+      (prev, next) {
+        if (prev == GamebookState.correctMove && next == GamebookState.findTheMove) {
+          _hideHint();
+        }
+      },
+    );
+
+    ref.listen(
```
Comment (veloce) [inline lib/src/view/study/study_gamebook.dart:110]: Not sure having 2 `ref.listen` is better than a single one with no select. I'd tend to say no, but it's no big deal, let's keep it that way.

**Review by veloce — APPROVED** [review]
