### PR TITLE
fix chat messages disappearing when a move is made

### LINKED ISSUE #2495: Since 19.0 or 19.1, in game chats sent disappear
- I compose an in game chat
- I see it send
- I leave the window and go back in and it's no longer there
- After the game ends/it usually comes back

### LINKED ISSUE #2781: Chat not chatting
### What is the problem?

When I try to chat with someone my text just dissapears. I don't know if they are receiving my messages at all.

### Steps to reproduce the bug

1. Just click on 5+3 friendly match
2. Type any messages in chat
3. Message dissapers just like magic
4. No message to be seen anywhere

### App version

0.22.3

### Device Info

Samsung Galaxy A35 / Android 16

### Additional information

https://github.com/user-attachments/assets/9123c61a-ec06-4eb4-a126-1542c138af7d

### PR DESCRIPTION
**Pull request by tom-anders**
Closes #2495
Closes #2781

### CODE REVIEW

File: lib/src/model/chat/chat_controller.dart [hunk 1]
```diff
@@ -111,14 +111,20 @@ class ChatController extends AsyncNotifier<ChatState> {
       _subscription?.cancel();
     });
 
+    // Do NOT use ref.read() here, since we just need to get the initial messages.
```
Comment (veloce) [inline lib/src/model/chat/chat_controller.dart]: You wanted to say `ref.watch`

Comment (tom-anders) [reply lib/src/model/chat/chat_controller.dart]: Whoops, fixss
