### PR TITLE
fix: use buildScreenRoute when replacing AnalysisScreen

### LINKED ISSUE #2682: Enabling variants in standalone analysis (ie horde) turn background black and lock out the Backswipe
https://github.com/user-attachments/assets/eb2a7a37-dfd1-476c-93c1-76fa3968dbfc

### PR DESCRIPTION
**Pull request by tom-anders**
closes #2682

### CODE REVIEW

File: lib/src/view/analysis/analysis_screen.dart [hunk 1]
```diff
@@ -602,8 +602,9 @@ class _BottomBar extends ConsumerWidget {
                           .read(analysisControllerProvider(options).notifier)
                           .clearSavedStandaloneAnalysis();
                       Navigator.of(context, rootNavigator: true).pushReplacement(
-                        PageRouteBuilder<dynamic>(
-                          pageBuilder: (context, animation, secondaryAnimation) => AnalysisScreen(
+                        buildScreenRoute<dynamic>(
+                          context,
+                          screen: AnalysisScreen(
```
Comment (veloce) [inline lib/src/view/analysis/analysis_screen.dart:607]: I don't get the fix since you are not using the transitionDuration parameter introduced above.

Comment (tom-anders) [reply lib/src/view/analysis/analysis_screen.dart:607]: I *do* use it, it's just that the PageRouteBuilder also has a parameter with that exact name, so it doesn't show up in the diff. See line 610

Comment (tom-anders) [reply lib/src/view/analysis/analysis_screen.dart:607]: A bit more context: When implementing changing the variant, I initially used `Navigator.of(context, rootNavigator: true).pushReplacement(buildScreenRoute<dynamic>(...)`. However, it looked a bit weird because of the transition animation. That's why I switched to `Navigator.of(context, rootNavigator: true).pushReplacement(PageRouteBuilder<dynamic>(...)` because of the `transitionDuration` parameter. But I didn't take into acount that not using `buildRoute` breaks the app's background. So that's why I switched to `buildRoute` here and added the `transitionDuration` parameter to that function.
