### PR TITLE
fix: respect "hide rating" pref in puzzle solution screen

### LINKED ISSUE #874: With ratings not showing, puzzle ratings show after solve
### What is the problem?

After disabling the show ratings option, one can still see the rating of the puzzle once it has been solved.
image

### Steps to reproduce the bug

1. Disable "show ratings" in the options
2. Solve a puzzle
3. Puzzle rating shows at the top

### What did you expect to happen?

Rating shouldn't show

### What happened instead?

Rating showed

### Device Info

Oneplus 7 pro

### Operating System Version

Android 12

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tom-anders**
Closes #874

with ratings disabled:
Screenshot_1722017687

### CODE REVIEW

File: test/view/puzzle/puzzle_screen_test.dart [hunk 1]
```diff
@@ -263,6 +265,7 @@ void main() {
         when(() => mockHistoryStorage.fetch(puzzleId: puzzle2.puzzle.id))
             .thenAnswer((_) async => puzzle2);
 
+        bool showRatings = true;
```
Comment (tom-anders) [inline test/view/puzzle/puzzle_screen_test.dart:268]: there's probably a more idiomatic way to do this...?

**Review by veloce — APPROVED** [review]
