### PR TITLE
only show next correct move when viewing puzzle solution

### LINKED ISSUE #761: Puzzles: show next correct move
I quite liked the way that the old app only gave you the next correct move in a puzzle when you tapped "show solution". That enabled me to think about the next move in the sequence until I had the puzzle fully solved, even though it was counted as wrong.
Would it be feasible to add a "show next move" button in addition to the "show solution" that is there, currently?

### PR DESCRIPTION
**Pull request by Mauritz8**
close #761 
This alters the "show solution button" to only show the next move in the solution, which is in line with both the website and the old app.

### CODE REVIEW

**Review by juan-campuzano — APPROVED** [review]

File: lib/src/model/puzzle/puzzle_controller.dart [hunk 1]
```diff
@@ -181,14 +181,7 @@ class PuzzleController extends _$PuzzleController {
...
     );
 
-    _viewSolutionTimer =
-        Timer.periodic(const Duration(milliseconds: 800), (timer) {
-      if (state.canGoNext) {
-        _goToNextNode();
-      } else {
-        timer.cancel();
-      }
-    });
```
Comment (veloce) [inline lib/src/model/puzzle/puzzle_controller.dart:191]: I think a slight delay before jumping to next move is still desirable.

**Review by veloce — COMMENTED** [review]
I think we want this but we could improve it a little more.

We could for instance have the forward button glow or blink for a short period (3s) to visually indicate that one can go forward.

There is already an example of blinking button in game screen when a draw offer is received.

**Comment by Mauritz8** [comment]
> There is already an example of blinking button in game screen when a draw offer is received.

For me the draw offer button is just colored differently, it doesn't blink or anything like that. 
Is there another example of a blinking button?
image

**Comment by veloce** [comment]
It doesn't blink? My bad then :)

Any visual indication would be good actually, blinking is not mandatory. Perhaps a simple background color inversion for a duration of 3s would be the best?

**Comment by veloce** [comment]
If you have the time to post a screen recording showing the feature and button visual indicator in action that would be great. Thanks!

**Comment by Mauritz8** [comment]
I tried both blinking and color inversion, and I think blinking works a lot better. And I set the duration to 5 seconds instead of 3 because it felt a bit too short.
[Screencast from 2024-07-05 12:20:21.webm](https://github.com/lichess-org/mobile/assets/67279312/7718e7d1-8d57-4864-a95c-6550646034cb)

File: lib/src/widgets/bottom_bar_button.dart [hunk 2]
```diff
@@ -64,10 +66,16 @@ class BottomBarButton extends StatelessWidget {
                   mainAxisAlignment: MainAxisAlignment.center,
                   crossAxisAlignment: CrossAxisAlignment.center,
                   children: [
-                    Icon(
-                      icon,
-                      color: highlighted ? primary : null,
-                    ),
+                    if (blink) ...[
```
Comment (veloce) [inline lib/src/widgets/bottom_bar_button.dart:69]: As there is a single child, I don't think the `...[` is necessary.

File: lib/src/widgets/bottom_bar_button.dart [hunk 3]
```diff
@@ -64,10 +66,16 @@ class BottomBarButton extends StatelessWidget {
...
+                      _BlinkIcon(
+                        icon: icon,
+                        color: highlighted
+                            ? primary
+                            : Theme.of(context).iconTheme.color ?? Colors.black,
+                      ),
+                    ] else ...[
```
Comment (veloce) [inline lib/src/widgets/bottom_bar_button.dart:76]: Same: unecessary `...[`

File: test/view/puzzle/puzzle_screen_test.dart [hunk 4]
```diff
@@ -415,11 +415,11 @@ void main() {
         await tester.tap(find.byIcon(Icons.help));
 
         // wait for solution replay animation to finish
-        await tester.pump(const Duration(seconds: 3));
+        await tester.pump(const Duration(seconds: 1));
         await tester.pumpAndSettle();
 
         expect(find.byKey(const Key('h4-blackRook')), findsOneWidget);
-        expect(find.byKey(const Key('h8-whiteQueen')), findsNothing);
+        expect(find.byKey(const Key('h8-whiteQueen')), findsOneWidget);
```
Comment (veloce) [inline test/view/puzzle/puzzle_screen_test.dart:422]: We could add another check to show the "jump to next move" button is not disabled.

**Comment by Mauritz8** [comment]
I addressed your comments. I'm a bit uncertain about the test, it might not be done in the most idiomatic way.

**Review by veloce — APPROVED** [review]

**Comment by veloce** [comment]
Thanks!
